<section id="navbar">  
		<nav>
			<a href="index.php">Index</a>  &nbsp;  &nbsp; &nbsp; &nbsp;   
			<a href="topic.php">Topic </a> &nbsp;  &nbsp; &nbsp; &nbsp;
			<a href="quiz.php">Quiz</a> &nbsp;  &nbsp; &nbsp; &nbsp;
			<a href="manage.php">Manage Quiz</a> &nbsp;  &nbsp; &nbsp; &nbsp;
			<a href="enhancements.php">Enhancements</a>&nbsp;  &nbsp; &nbsp; &nbsp;
			<a href="enhancements2.php">Enhancements2</a>&nbsp;  &nbsp; &nbsp; &nbsp;
			<a href="enhancements3.php">Enhancements3</a>&nbsp;  &nbsp; &nbsp; &nbsp;
			<a href="about.php">About Us</a>&nbsp;  &nbsp; &nbsp; &nbsp;
		</nav>  
	</section>